version: 1.2
workflows:
- name: 'COVID-19 variation analysis on Illumina metagenomic data'
  primaryDescriptorPath: workflows/sars-cov-2-variant-calling/workflow.ga
  subclass: Galaxy
  testParameterFiles:
  - workflows/sars-cov-2-variant-calling/workflow-test.yml
